site_name: DOCUMENTATION
theme:
  name: material
  custom_dir: docs/overrides
  language: fr
  favicon: https://www.codepuzzle.io/img/favicon.png
  logo: https://www.codepuzzle.io/img/favicon.png
  palette:
    primary: white
    accent: light blue
  icon:
    repo: fontawesome/brands/git-alt
  font:
    text: Roboto
  features:
    - navigation.tabs
    - content.tabs.link    
    - toc.integrate
    - navigation.top
    - navigation.instant
    - navigation.tracking

extra:
  version:
    provider: mike
    
repo_url: https://github.com/codepuzzle-io/documentation
edit_uri: ""

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences   
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg   
  - admonition
  - pymdownx.details   
  - attr_list
  - md_in_html
  - abbr
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde  
 
extra_css:
  - assets/stylesheets/extra.css 
 
extra_javascript:
  - assets/javascripts/extra.js 
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
